# This file was programmatically generated from JSON Schemas.
# Generated on: 2025-09-24T16:13:25.575
# Do not edit this file directly.

"""
    CombinedSchemaExample

A single schema demonstrating oneOf, anyOf, allOf, and not.

Fields:
    `not_a_password`: A password that cannot be the literal string 'password'.
    `any_of_identifier`: Demonstrates 'anyOf' for a product identifier.
    `one_of_user`: Demonstrates 'oneOf' for a user that is either a Person or a Company.
    `all_of_request`: Demonstrates 'allOf' to combine schemas for a request with authentication.

"""
struct CombinedSchemaExample
    not_a_password::Any # The type of this field is constrained by a 'not' keyword and must be validated at runtime.
    any_of_identifier::Union{CombinedSchemaExampleAnyOfIdentifier, CombinedSchemaExampleAnyOfIdentifier}
    one_of_user::Union{CombinedSchemaExampleOneOfUser, CombinedSchemaExampleOneOfUser}
    all_of_request::Any
end
