# This file was programmatically generated from JSON Schemas.
# Generated on: 2025-09-24T18:41:01.843
# Do not edit this file directly.

"""
    ComplexEnumExampleOrderStatus

The current status of the entire order.

Fields:
    `priority`: The priority level of the order.

"""
struct ComplexEnumExampleOrderStatus
    priority::Int64
    payment_status::PaymentStatus
end

"""
    ComplexEnumExampleProduct

A product with a nested shipping status.

Fields:
    `shipping_status`: The current shipping status of the product.

"""
struct ComplexEnumExampleProduct
    shipping_status::String
    id::String
end

"""
    PaymentStatus

The status of a payment, defined as a reusable component.
"""
struct PaymentStatus
end

"""
    ComplexEnumExample

An example schema to test deeply nested enumerated types within objects and references.

Fields:
    `order_status`: The current status of the entire order.
    `product`: A product with a nested shipping status.

"""
struct ComplexEnumExample
    order_status::ComplexEnumExampleOrderStatus
    product::ComplexEnumExampleProduct
end
