# This file was programmatically generated from JSON Schemas.
# Generated on: 2025-09-23T22:15:29.601
# Do not edit this file directly.

"""
    Customer


"""
struct Customer
    name::String
    id::Int64
    email::Union{Nothing, String}
end

# The field `customer` in this struct depends on a type `Customer` from `customer_schema.json`
"""
    Items


"""
struct Items
    productId::String
    quantity::Int64
end

"""
    Order


"""
struct Order
    items::Vector{Items}
    customer::Customer
    orderId::String
end
