# This file was programmatically generated from JSON Schemas.
# Generated on: 2025-09-23T09:12:02.320
# Do not edit this file directly.

struct Customer
    name::String
    id::Int64
    email::Union{Nothing, String}
end

struct Customer
    name::String
    id::Int64
    email::Union{Nothing, String}
end

# Depends on struct Customer from customer_schema.json
struct Items
    productId::String
    quantity::Int64
end

struct Order
    items::Vector{Items}
    customer::Customer
    orderId::String
end
