# This file was programmatically generated from JSON Schemas.
# Generated on: 2025-09-24T08:52:48.721
# Do not edit this file directly.

"""
    Customer


"""
struct Customer
    name::String
    id::Int64
    email::Union{Nothing, String}
end

"""
    OrderItem


"""
struct OrderItem
    productId::String
    quantity::Int64
end

"""
    Order


"""
struct Order
    items::Vector{OrderItem}
    customer::Customer
    orderId::String
end
