# This file was programmatically generated from JSON Schemas.
# Generated on: 2025-09-25T08:47:52.940
# Do not edit this file directly.

"""
    Person


"""
struct Person
    first_name::String
    user_type::String
    last_name::String
end

"""
    Company


"""
struct Company
    company_name::String
    user_type::String
end

"""
    AnyOfIdentifierAnyOf1


"""
struct AnyOfIdentifierAnyOf1
    sku::String
end

"""
    AnyOfIdentifierAnyOf2


"""
struct AnyOfIdentifierAnyOf2
    product_code::String
end

"""
    CombinedSchemaExample

A single schema demonstrating oneOf, anyOf, allOf, and not.

Fields:
    `not_a_password`: A password that cannot be the literal string 'password'.
    `any_of_identifier`: Demonstrates 'anyOf' for a product identifier.
    `one_of_user`: Demonstrates 'oneOf' for a user that is either a Person or a Company.
    `all_of_request`: Demonstrates 'allOf' to combine schemas for a request with authentication.

"""
struct CombinedSchemaExample
    not_a_password::Any # The type of this field is constrained by a 'not' keyword and must be validated at runtime.
    any_of_identifier::Union{CombinedSchemaExampleAnyOfIdentifierAnyOf1, CombinedSchemaExampleAnyOfIdentifierAnyOf2}
    one_of_user::Union{CombinedSchemaExampleOneOfUserOneOf1, CombinedSchemaExampleOneOfUserOneOf2}
    all_of_request::Any
end
