# This file was programmatically generated from JSON Schemas.
# Generated on: 2025-09-25T09:54:31.207
# Do not edit this file directly.

"""
    OrderItems


"""
struct OrderItems
    productId::String
    quantity::Int64

    function OrderItems(productId::String, quantity::Int64)
        @assert quantity >= 4 "'quantity' must be at least 4"
        @assert quantity < 20 "'quantity' must be less than 20"
        @assert quantity % 2 == 0 "'quantity' must be a multiple of 2"
        new(productId, quantity)
    end
end

"""
    Customer


"""
struct Customer
    name::String
    id::Int64
    email::Union{Nothing, String}
end

"""
    Order


"""
struct Order
    items::Vector{OrderItems}
    # Depends on Customer from customer_schema.json
    customer::Customer
    orderId::String
end
